import type { Metadata } from "next";
import { Geist, Geist_Mono, Prompt } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { ToastProvider } from "@/providers/ToastProvider";
import { K2D } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const prompt = Prompt({
  subsets: ["thai"],
  variable: "--font-prompt",
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const k2d = K2D({
  variable: "--font-k2d",
  subsets: ["thai", "latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${prompt.variable} ${k2d.variable} antialiased overflow-x-hidden`}
      >
        <QueryProvider>
          {/* <Toaster
            position={toastPosition}
            toastOptions={{
            
              className: "font-bold border-2 border-black rounded-xl shadow-lg",
              duration: 3000,
             
              success: {
                className: "bg-white border-cprojectone text-black h-20 px-6",
              },
            }}
          /> */}
          {children}
          <ToastProvider />
        </QueryProvider>
      </body>
    </html>
  );
}
